name: kubernetes-deploy
on:
  push:
    branches: [ main ]
env:
  CLOUDSDK_CORE_DISABLE_PROMPTS: 1   
  SHA: $(git rev-parse HEAD) 
jobs:
  build:
    name: react test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: setup gcloud
      run: | 
        echo "the current commit sha is ${{github.sha}} and ${{secrets.SHA}}"
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSPHRASE }}" --output service-account.json service-account.json.gpg
        curl https://sdk.cloud.google.com | bash > /dev/null;
        source $HOME/google-cloud-sdk/path.bash.inc
        gcloud components update kubectl
        gcloud auth activate-service-account --key-file service-account.json
        gcloud config set project kubernetes-basics-369813
        gcloud config set compute/zone asia-east1-a
        gcloud container clusters get-credentials muti-cluster
    - name: setup docker 
      run : |
        echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
        docker build -t bipen2001/react-test -f ./client/Dockerfile.dev ./client
    - name: run react docker test
      run : |
        docker build -t bipen2001/react-test -f ./client/Dockerfile.dev ./client    

    - name: deploy
      run: |
        bash ./deploy.sh
